name: "Common Checks"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linter_checks:
    continue-on-error: False
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:  |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install
    - name: Check code quality
      run: make code-check

  test:
    continue-on-error: True
    needs:
      - linter_checks
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ "3.10" ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install
      - name: Run unit tests
        run: poetry run pytest tests
